#ifndef PPG_CONST_H
#define PPG_CONST_H

#define FPS 60
#define SCREEN_WIDTH 780
#define SCREEN_HEIGHT 600
#define BALL_WIDTH 50
#define BALL_HEIGHT 50
#define BALL_VELOCITY 5
#define PLAYER_WIDTH 30
#define PLAYER_HEIGHT 150
#define PLAYER_VELOCITY 6
#define MAX_POINTS 12
#define KEY_RELEASED 900
#define FONT_SIZE 500
#define MOUSE_BUTTON_PRESSED 645
#define EXIT_GAME 123
#define PLAY_GAME 345
#define RET_TO_MENU 657

#endif
